algoritmo "Exercicio01"
// Função : Calcular Média de Três Valores
// Autor : Daniel Vidiri Neto (109970)
// Data : 10/03/2020
// Seção de Declarações 
var
   N1, N2, N3: inteiro
   Media: real
inicio
// Seção de Comandos
   Escreva ("Digite o Primeiro Valor: ")
   Leia (N1)
   Escreval ("Digite o Segundo Valor: ")
   Leia (N2)
   Escreva ("Digite o Terceiro Valor: ")
   Leia (N3)
   Media <- (N1 + N2 + N3) / 3
   
   Escreva ("Média: ", Media)
fimalgoritmo
