algoritmo "Exercicio05"
// Função : URI 1010 - Cálculo Simples
// Autor : Daniel Vidiri Neto
// Data : 11/03/2020
// Seção de Declarações 
var
   cod1, quant1, cod2, quant2: inteiro
   valor1, valor2, soma: real
inicio
// Seção de Comandos
   Leia (cod1, quant1, valor1)
   Leia (cod2, quant2, valor2)
   soma <- ((valor1*quant1) + (valor2*quant2))

   Escreva ("VALOR A PAGAR: R$ ", soma:3:2)
   
fimalgoritmo
