algoritmo "TAREFA15"
// Função : SEIS NÚMEROS ÍMPARES
// Autor : DANIEL VIDIRI NETO
// Data : 10/04/2020
// Seção de Declarações 
var
   x, i: inteiro
inicio
// Seção de Comandos
   Escreva("Digite um Valor Inteiro e Positivo: ")
   Leia(x)
   
   PARA i DE 1 ATE 12 PASSO 1 FACA
        SE (X MOD 2 <> 0) ENTAO
           Escreval(x)
        FIMSE
        x <- x + 1
   FIMPARA
fimalgoritmo
